(module rom)

(defcolumns 
  (CODE_FRAGMENT_INDEX :i32)
  (CODE_FRAGMENT_INDEX_INFTY :i32)
  (CODE_SIZE :i32)
  (CODESIZE_REACHED :binary)
  (PROGRAM_COUNTER :i32)
  LIMB
  (nBYTES :byte)
  (nBYTES_ACC :byte)
  INDEX
  (COUNTER :byte)
  (COUNTER_MAX :byte)
  (PADDED_BYTECODE_BYTE :byte)
  ACC
  (IS_PUSH :binary)
  PUSH_PARAMETER
  (COUNTER_PUSH :byte)
  (IS_PUSH_DATA :binary)
  PUSH_VALUE_HIGH
  PUSH_VALUE_LOW
  PUSH_VALUE_ACC
  (PUSH_FUNNEL_BIT :binary)
  (OPCODE :byte :display :opcode)
  (VALID_JUMP_DESTINATION :binary))

(defalias 
  PC   PROGRAM_COUNTER
  CFI  CODE_FRAGMENT_INDEX
  CT   COUNTER
  PBCB PADDED_BYTECODE_BYTE)


