(module bls)

(defun (phase_sum)
    (+ (* PHASE_DATA_POINT_EVALUATION DATA_POINT_EVALUATION_FLAG)
       (* PHASE_RSLT_POINT_EVALUATION RSLT_POINT_EVALUATION_FLAG)
       (* PHASE_DATA_G1_ADD DATA_BLS_G1_ADD_FLAG)
       (* PHASE_RSLT_G1_ADD RSLT_BLS_G1_ADD_FLAG)
       (* PHASE_DATA_G1_MSM DATA_BLS_G1_MSM_FLAG)
       (* PHASE_RSLT_G1_MSM RSLT_BLS_G1_MSM_FLAG)
       (* PHASE_DATA_G2_ADD DATA_BLS_G2_ADD_FLAG)
       (* PHASE_RSLT_G2_ADD RSLT_BLS_G2_ADD_FLAG)
       (* PHASE_DATA_G2_MSM DATA_BLS_G2_MSM_FLAG)
       (* PHASE_RSLT_G2_MSM RSLT_BLS_G2_MSM_FLAG)
       (* PHASE_DATA_PAIRING_CHECK DATA_BLS_PAIRING_CHECK_FLAG)
       (* PHASE_RSLT_PAIRING_CHECK RSLT_BLS_PAIRING_CHECK_FLAG)
       (* PHASE_DATA_MAP_FP_TO_G1 DATA_BLS_MAP_FP_TO_G1_FLAG)
       (* PHASE_RSLT_MAP_FP_TO_G1 RSLT_BLS_MAP_FP_TO_G1_FLAG)
       (* PHASE_DATA_MAP_FP2_TO_G2 DATA_BLS_MAP_FP2_TO_G2_FLAG)
       (* PHASE_RSLT_MAP_FP2_TO_G2 RSLT_BLS_MAP_FP2_TO_G2_FLAG)))

(defconstraint stamp-constancy ()
    (stamp-constancy STAMP PHASE))

(defconstraint setting-phase ()
    (eq! PHASE (phase_sum)))

    
   
   
   