(module mxpcan)


(defconst
  ROW_OFFSET___DECDR_TO_MACRO   1
  ROW_OFFSET___DECDR_TO_SCNRI   2
  ROW_OFFSET___MACRO_TO_SCNRI   1
  ;;
  ROW_OFFSET___MACRO_TO_DECDR   ROW_OFFSET___DECDR_TO_MACRO
  ROW_OFFSET___SCNRI_TO_DECDR   ROW_OFFSET___DECDR_TO_SCNRI
  ROW_OFFSET___SCNRI_TO_MACRO   ROW_OFFSET___MACRO_TO_SCNRI
  ;;
  NEGATIVE_ROW_OFFSET___SCNRI_TO_DECDR   (- 0 ROW_OFFSET___SCNRI_TO_DECDR)
  NEGATIVE_ROW_OFFSET___SCNRI_TO_MACRO   (- 0 ROW_OFFSET___SCNRI_TO_MACRO)
  )

