(module mxp)
(defcolumns
	MEMORY_EXPANSION_STAMP
	MEMORY_EXPANSION_TYPE
	(MEMORY_EXPANSION_EXCEPTION	:BOOLEAN)
	(RIDICULOUSLY_OUT_OF_BOUND	:BOOLEAN)
	(NOOP	:BOOLEAN)
	COUNTER
	CN
	VAL_1_HI
	VAL_1_LO
	VAL_2_HI
	VAL_2_LO
	VAL_3_HI
	VAL_3_LO
	VAL_4_HI
	VAL_4_LO
	LAST_OFFSET_1
	LAST_OFFSET_2
	(BYTE :byte :array[0:8])
	(ACC :array[0:6])
	MSIZE
	MSIZE_NEW
	MEMORY_EXPANSION_COST
	MEMORY_EXPANSION_COST_NEW
	DELTA_MEMORY_EXPANSION_COST
	SIZE_IN_EVM_WORDS
	(COMP	:BOOLEAN)
	MAX_OFFSET
	(MEMORY_EXPANSION_EVENT	:BOOLEAN))

;; aliases
(defalias
	STAMP		MEMORY_EXPANSION_STAMP
	MXT			MEMORY_EXPANSION_TYPE
	MXX			MEMORY_EXPANSION_EXCEPTION
	ROOB		RIDICULOUSLY_OUT_OF_BOUND
	CT			COUNTER
	MXC			MEMORY_EXPANSION_COST
	MXC_NEW		MEMORY_EXPANSION_COST_NEW
	DELTA_MXC	DELTA_MEMORY_EXPANSION_COST
	SEVMW		SIZE_IN_EVM_WORDS
	MXE			MEMORY_EXPANSION_EVENT)