(module mxp)

(defcolumns
	MEMORY_EXPANSION_STAMP
	MEMORY_EXPANSION_TYPE
	(MEMORY_EXPANSION_EXCEPTION	:BOOLEAN)
	(RIDICULOUSLY_OUT_OF_BOUND	:BOOLEAN)
	(NOOP	:BOOLEAN)
	COUNTER
	CN
	VAL_HIGH_1
	VAL_LOW_1
	VAL_HIGH_2
	VAL_LOW_2
	VAL_HIGH_3
	VAL_LOW_3
	VAL_HIGH_4
	VAL_LOW_4
	(BYTE_0 :BYTE)
	(BYTE_1 :BYTE)
	(BYTE_2 :BYTE)
	(BYTE_3 :BYTE)
	(BYTE_4 :BYTE)
	(BYTE_5 :BYTE)
	(BYTE_6 :BYTE)
	(BYTE_7 :BYTE)
	(BYTE_8 :BYTE)
	ACC_1
	ACC_2
	ACC_3
	ACC_4
	ACC_5
	ACC_6
	MSIZE
	MSIZE_NU
	MEMORY_EXPANSION_COST
	MEMORY_EXPANSION_COST_NU
	DELTA_MEMORY_EXPANSION_COST
	SIZE_IN_EVM_WORDS
	(COMP	:BOOLEAN)
	MAX_OFFSET
	(MEMORY_EXPANSION_EVENT	:BOOLEAN))

;; aliases
(defalias
	STAMP		MEMORY_EXPANSION_STAMP
	MXT			MEMORY_EXPANSION_TYPE
	MXX			MEMORY_EXPANSION_EXCEPTION
	ROOB		RIDICULOUSLY_OUT_OF_BOUND
	CT			COUNTER
	MXC			MEMORY_EXPANSION_COST
	MXC_NU		MEMORY_EXPANSION_COST_NU
	DELTA_MXC	DELTA_MEMORY_EXPANSION_COST
	SEVMW		SIZE_IN_EVM_WORDS
	MXE			MEMORY_EXPANSION_EVENT)