(module rlptxn)

(defun (rlp-compound-integer w integer-hi integer-lo is-end-of-phase)
    (begin 
    (eq! (shift CT_MAX                                      w)      RLP_TXN_CT_MAX_INTEGER)
    (eq! (shift PHASE_END  (+ w (- RLP_TXN_CT_MAX_INTEGER 1)))      is-end-of-phase)
    (rlputils-call-integer                                   w      integer-hi integer-lo)
    (conditionally-set-limb                                  w      (rlptxn---integer-out-rlp-prefix-required w) 
                                                                    (rlptxn---integer-out-rlp-prefix w) 
                                                                    1)
    (conditionally-set-limb                            (+ w 1)      (rlptxn---integer-out-integer-has-non-zero-hi-part w) 
                                                                    (rlptxn---integer-out-leading-limb-left-shifted w) 
                                                                    (rlptxn---integer-out-leading-limb-byte-size w))
    (conditionally-set-limb                            (+ w 2)      (rlptxn---integer-out-integer-is-non-zero w) 
                                                                    (rlptxn---integer-last-limb integer-lo w) 
                                                                    (rlptxn---integer-last-limb-byte-size w))
    ))

(defun (rlptxn---integer-out-integer-is-non-zero w)                         (shift cmp/EXO_DATA_3 w))
(defun (rlptxn---integer-out-integer-has-non-zero-hi-part w)                (shift cmp/EXO_DATA_4 w))
(defun (rlptxn---integer-out-rlp-prefix-required w)                         (shift cmp/EXO_DATA_5 w))
(defun (rlptxn---integer-out-rlp-prefix w)                                  (shift cmp/EXO_DATA_6 w))
(defun (rlptxn---integer-out-leading-limb-left-shifted w)                   (shift cmp/EXO_DATA_7 w))
(defun (rlptxn---integer-out-leading-limb-byte-size w)                      (shift cmp/EXO_DATA_8 w))
(defun (rlptxn---integer-last-limb integer-lo w)  
    (if-zero (rlptxn---integer-out-integer-has-non-zero-hi-part w)
        (rlptxn---integer-out-leading-limb-left-shifted w)
        integer-lo))
(defun (rlptxn---integer-last-limb-byte-size w)  
    (if-zero (rlptxn---integer-out-integer-has-non-zero-hi-part w)
        (rlptxn---integer-out-leading-limb-byte-size w)
        LLARGE))