(module rlptxn)  
        
 (defun (first-row-of-rlp-prefix              )       (* IS_RLP_PREFIX               TXN))
 (defun (first-row-of-chain-id                )       (* IS_CHAIN_ID                 TXN))
 (defun (first-row-of-nonce                   )       (* IS_NONCE                    TXN))
 (defun (first-row-of-gas-price               )       (* IS_GAS_PRICE                TXN))
 (defun (first-row-of-max_priority-fee-per-gas)       (* IS_MAX_PRIORITY_FEE_PER_GAS TXN))
 (defun (first-row-of-maw-fee-per-gas         )       (* IS_MAX_FEE_PER_GAS          TXN))
 (defun (first-row-of-gas-limit               )       (* IS_GAS_LIMIT                TXN))
 (defun (first-row-of-to                      )       (* IS_TO                       TXN))
 (defun (first-row-of-value                   )       (* IS_VALUE                    TXN))
 (defun (first-row-of-data                    )       (* IS_DATA                     TXN))
 (defun (first-row-of-access-list             )       (* IS_ACCESS_LIST              TXN))
 (defun (first-row-of-beta                    )       (* IS_BETA                     TXN))
 (defun (first-row-of-y                       )       (* IS_Y                        TXN))
 (defun (first-row-of-r                       )       (* IS_R                        TXN))
 (defun (first-row-of-s                       )       (* IS_S                        TXN))