(module precompile_info)

(defcolumns
  STAMP
  ADDR_LO
  GAS_STPD
  CALL_DATA_SIZE
  (EC_DATA_CHECKS_PASSED :boolean)
  MODEXP_PARAMS
  BLAKE_F
  BLAKE_ROUNDS
  (SUCCESS :boolean)
  RETURN_DATA_SIZE
  GAS_RETURNED
  (PROVIDES_RETURN_DATA :boolean)
  (TOUCHES_RAM :boolean)
  PAIRING_COUNT
  MOD_ARG1_LO
  MOD_ARG2_LO
  MOD_RES
  WCP_ARG1_LO
  WCP_ARG2_LO
  WCP_RES
  COUNTER
  (EC_RECOVER :boolean)
  (SHA2 :boolean)
  (RIPEMD :boolean)
  (IDENTITY :boolean)
  (MODEXP :boolean)
  (EC_ADD :boolean)
  (EC_MUL :boolean)
  (EC_PAIRING :boolean)
  (BLAKE :boolean)
  CONSUMED_GAS
  (ENOUGH_GAS :boolean)
  (MALFORMED_DATA :boolean)
  CALL_DATA_WORDS
  (MODEXP_BYTES :byte)
  MODEXP_BYTE_ACC
  (MODEXP_BYTE_SWITCH :byte)
  MODEXP_BYTE_SWITCH_INDEX
  (MODEXP_E_LEADING_WORD_FIRST_BYTE :byte)
  (MODEXP_BITS :boolean)
  MODEXP_BIT_ACC
  (MODEXP_BIT_SWITCH :byte)
  MODEXP_BIT_SWITCH_INDEX
  MODEXP_E_LEADING_WORD_BIT_LENGTH
  MODEXP_E_LEADING_WORD_LOG
  MODEXP_LE_PRIME
  MODEXP_MAX_LE_PRIME_AND_1
  MODEXP_BIG_FRACTION
  (TRANSMITS_PAIRING_COUNT_TO_ECDATA :boolean))
