(module ec_data)

(defcolumns 
  (STAMP :i3)
  (INDEX :byte)
  (CT_MIN :byte)
  (LIMB :i16)
  (TYPE :byte)
  (EC_RECOVER :binary@prove)
  (EC_ADD :binary@prove)
  (EC_MUL :binary@prove)
  (EC_PAIRING :binary@prove)
  (TOTAL_PAIRINGS :i2)
  (ACC_PAIRINGS :i2)
  (COMPARISONS :binary@prove)
  (EQUALITIES :binary@prove)
  (HURDLE :binary@prove)
  (PRELIMINARY_CHECKS_PASSED :binary@prove)
  (ALL_CHECKS_PASSED :binary@prove)
  (SQUARE :i16)
  (CUBE :i16)
  (BYTE_DELTA :byte@prove)
  (ACC_DELTA :i16)
  (WCP_ARG1_HI :i16)
  (WCP_ARG1_LO :i16)
  (WCP_ARG2_HI :i16)
  (WCP_ARG2_LO :i16)
  (WCP_INST :byte :display :opcode)
  (WCP_RES :binary)
  (EXT_ARG1_HI :i16)
  (EXT_ARG1_LO :i16)
  (EXT_ARG2_HI :i16)
  (EXT_ARG2_LO :i16)
  (EXT_ARG3_HI :i16)
  (EXT_ARG3_LO :i16)
  (EXT_INST :byte :display :opcode)
  (EXT_RES_LO :i16)
  (EXT_RES_HI :i16)
  (THIS_IS_NOT_ON_G2 :binary@prove)
  (THIS_IS_NOT_ON_G2_ACC :binary@prove)
  (SOMETHING_WASNT_ON_G2 :binary@prove))

;; aliases
(defalias 
  PCP PRELIMINARY_CHECKS_PASSED)


